### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by emilianocorvi** [maketechnology/cefswt#4]
by emiliano.corvi

**Comment by nedtwigg** [comment]
I think the top of the README should have the simplest-possible build instructions to get a running example.  I'd like to have that working before I send traffic here.  From what I can tell, those instructions should be:

> To see a running example, run `gradlew writeProps buildSampleE4` then you can run the application in `com.make.cef.sample.e4.ecp/target/products/cef_rcp/<platform>/cef_rcp`

Right now, this works for me on mac.  On linux, the e4 window opens, but does not display a browser.  I get this at the console:

```
bundleFolder: linux-x86_64
swtcef path: /home/ntwigg/.swtcef/3.3029.1611.g44e39a8
Expanded CEF natives to /home/ntwigg/.swtcef/3.3029.1611.g44e39a8
J:paintControl
J:SIZEOF:App:72
J:SIZEOF:BrowserProcessHandler:72
cefrust.path: /home/ntwigg/.swtcef/3.3029.1611.g44e39a8/linux-x86_64
DLL init
Hello CEF, ARGS: 0
Some("/home/ntwigg/.swtcef/3.3029.1611.g44e39a8/linux-x86_64")
subp: "/home/ntwigg/.swtcef/3.3029.1611.g44e39a8/linux-x86_64/cefrust_subp"
initialize_CefBase
cef_base_t.size = 72
Calling cef_initialize
[0606/103843.663168:ERROR:icu_util.cc(173)] Invalid file descriptor to ICU data received.
```

On windows, I also get an empty e4 window, but there's no console output.

Am I doing something wrong?

**Comment by gzunino** [comment]
I think linux doesn't work due https://bitbucket.org/chromiumembedded/cef/issues/1936/override-paths-dir_exe-dir_module-on-linux.
You can copy icudtl.dat, natives_blob.bin and snapshot_blob.bin  from CEF to jre/bin folder, those files should be siblings of the java executable file.
Not sure about windows,  probably some missing steps during build.

**Comment by dcentri** [comment]
Hi,
I followed through @emilianocorvi  readme [https://github.com/maketechnology/cefswt/blob/965cf7c4de7d7b7e07fbd5884311eb0ef4456941/README.md](url) to try and build the sample application on my system(windows 10 x64). I managed to get a successful build but i get runtime unresolved compilation errors 

> The import jnr.ffi.LibraryLoader cannot be resolved
> The import jnr.ffi.Pointer cannot be resolved
> The import jnr.ffi.annotations cannot be resolved

Running the .exe i get the same results as @nedtwigg  e4 window but the browser doesn't load

> Direct cannot be resolved to a type

	at com.make.swtcef.Chromium.<init>(Chromium.java:29)
	at com.make.cef.sample.e4.CefPart.postConstruct(CefPart.java:42)

[https://gitlab.com/maketechnology/jres/builds/12670474/artifacts/download](url) is not available anymore so i wasn't able to include it in my project but everything else seems to be in place. 

Are there any missing steps? Is there any additional libraries that i should include to resolve `jnr.ffi.LibraryLoader` ?

**Comment by gzunino** [comment]
Hi @dcentri, for now the instructions are not complete to build it locally, as it requires some prerequisites not documented. Demo binaries are available to download. Full build instructions will be provided as we move the project to eclipse, depending if we get enough funding.

**Comment by zrqhxm** [comment]
Hi! @dcentri ,i don't know how to build this project use eclipse,can u tell me?  and i meet the same problem with u about jnr.ffi ,if u solve it?

**Comment by joehongfly** [comment]
just run com.make.cef.CefOsgiApp.main() and need set systemproperty"cefswt.path"to your correct path

**Comment by zrqhxm** [comment]
@joehongfly thanks for your answer.
i import this project use eclipse maven,but there's a strange phenomenon at 'com.make.cef META-INF MANIFEST.MF' that 'Require-Bundle' show :
 "Bundle 'org.objectweb.asm.analysis' cannot be resolved","Bundle 'com.github.jnr.ffi' cannot be resolved","Bundle 'org.objectweb.asm.util' cannot be resolved","Bundle 'org.objectweb.asm.tree' cannot be resolved".
i try to Run As CefOsgiApp.main(),it doesn't show 'java application' and it just Run Configurations... and i 
cann't find which file set systemproperty"cefswt.path“.
i am going crazy...

**Comment by gzunino** [comment]
@zrqhxm 
If you need (paid) consultancy or support for having the widget integrated into your app, contact us (Make Technology, http://www.wemaketechnology.com) at guillez@gmail.com.

We're offering early support for the widget and consultancy. Note that it will be open source anyway.

**Comment by hthomann** [comment]
HI!  I agree here, the readme should be updated to tell a person how to run the sample.  I can download, unzip, and run cef_rcp.exe.  However, I don't see anything in the sample, i.e. I don't see the contents of the URL actually displayed.....I just see a blank/grey screen.  Is this the normal output?  I'm guessing not.  Oh, I'm on Windows 10 btw.

Thanks,
Heath Thomann
